name: CI / CD
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get install -y libgeos-c1v5
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11.x"
      - name: Install requirements
        run: |
          pip install -U pip
          pip install -U -r requirements.txt
          python setup.py build

      - name: Run Tests
        run: |
          pytest

  build:
    strategy:
      matrix:
        os: [macos, ubuntu, windows]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11.x"
      - name: Install requirements
        run: |
          pip install -U -r requirements.txt
      - name: Build binary
        run: |
          python setup.py build
          pyinstaller --onefile preprocess_cancellation.py
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: preprocess_cancellation-${{ matrix.os }}
          path: |
            dist

  release:
    runs-on: ubuntu-latest
    needs: [test, build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3

      - name: Release tags
        uses: softprops/action-gh-release@v1
        with:
          files: |
            */preprocess_cancellation-*.zip
